Repository WebChatting/chatting-vue, pull requests merged in 2023-03, with the labels that each got.

#5 ci(jenkins): add CD Jenkinsfile
  jenkins/Jenkinsfile
Labels: enhancement

#6 提供CI
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: enhancement

#18 Refactor/component
  src/components/MessageArea.vue
  src/components/MessageBottomInputArea.vue
  src/components/MessageTopTitle.vue
  src/components/NavigationTopSearchBar.vue
  src/components/NavigationZone.vue
  src/components/SearchArea.vue
  src/components/SearchAreaBody.vue
  src/pages/Chatting.vue
Labels: refactor

#21 Fix/message
  src/components/MessageArea.vue
  src/components/RelationList.vue
  src/store/index.js
Labels: bug

#23 修复ws无法连接的问题
  src/pages/Chatting.vue
  src/utils/socket.js
Labels: bug
